version: '3.9'

services:
  web:
    container_name: web
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8000:8000"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/code
    healthcheck:
      test: curl --fail http://0.0.0.0:8000/internal/health_check || exit 1
      interval: 5s
      timeout: 1s
      retries: 5
    depends_on:
      redis:
        condition: service_started
      web_db:
        condition: service_healthy
    networks:
      - layer_network

  web_db:
    container_name: web_db
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_db
    restart: on-failure
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "main_db" ]
      interval: 5s
      retries: 5
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - layer_network

  redis:
    container_name: redis
    image: redis:6.2.4
    ports:
      - "6379:6379"
    networks:
      - layer_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus_config.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - layer_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: grafana/.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - web
    networks:
      - layer_network

volumes:
  prom_data:

networks:
  layer_network:
    external: True
