"""empty message

Revision ID: 0ddf6ddb8e97
Revises: f2eec67057cb
Create Date: 2023-11-27 04:57:50.087443

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ddf6ddb8e97'
down_revision: Union[str, None] = 'f2eec67057cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['sirius.role.id'], name=op.f('fk_user_role_role_id_role')),
        sa.ForeignKeyConstraint(['user_id'], ['sirius.user.id'], name=op.f('fk_user_role_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_user_role_id'), 'user_role', ['id'], unique=True, schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sirius_user_role_id'), table_name='user_role', schema='sirius')
    op.drop_table('user_role', schema='sirius')
    # ### end Alembic commands ###
