"""empty message

Revision ID: 9947927c5511
Revises: 
Create Date: 2023-11-23 07:03:46.947321

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9947927c5511'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.Column('code', sa.String(length=128), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_user_email'), 'user', ['email'], unique=True, schema='sirius')
    op.create_index(op.f('ix_sirius_user_id'), 'user', ['id'], unique=True, schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sirius_user_id'), table_name='user', schema='sirius')
    op.drop_index(op.f('ix_sirius_user_email'), table_name='user', schema='sirius')
    op.drop_table('user', schema='sirius')
    # ### end Alembic commands ###
