"""empty message

Revision ID: f2eec67057cb
Revises: 9947927c5511
Create Date: 2023-11-25 08:46:27.556882

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2eec67057cb'
down_revision: Union[str, None] = '9947927c5511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_role_id'), 'role', ['id'], unique=True, schema='sirius')
    op.create_index(op.f('ix_sirius_role_name'), 'role', ['name'], unique=True, schema='sirius')
    op.create_table(
        'service',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=320), nullable=False),
        sa.Column('url', sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_service_id'), 'service', ['id'], unique=True, schema='sirius')
    op.create_index(op.f('ix_sirius_service_name'), 'service', ['name'], unique=True, schema='sirius')
    op.create_table(
        'path',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=320), nullable=False),
        sa.Column('path', sa.String(length=320), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('type', sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(['service_id'], ['sirius.service.id'], name=op.f('fk_path_service_id_service')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_path')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_path_id'), 'path', ['id'], unique=True, schema='sirius')
    op.create_table(
        'role_path',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('path_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['path_id'], ['sirius.path.id'], name=op.f('fk_role_path_path_id_path')),
        sa.ForeignKeyConstraint(['role_id'], ['sirius.role.id'], name=op.f('fk_role_path_role_id_role')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_role_path')),
        schema='sirius',
    )
    op.create_index(op.f('ix_sirius_role_path_id'), 'role_path', ['id'], unique=True, schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sirius_role_path_id'), table_name='role_path', schema='sirius')
    op.drop_table('role_path', schema='sirius')
    op.drop_index(op.f('ix_sirius_path_id'), table_name='path', schema='sirius')
    op.drop_table('path', schema='sirius')
    op.drop_index(op.f('ix_sirius_service_name'), table_name='service', schema='sirius')
    op.drop_index(op.f('ix_sirius_service_id'), table_name='service', schema='sirius')
    op.drop_table('service', schema='sirius')
    op.drop_index(op.f('ix_sirius_role_name'), table_name='role', schema='sirius')
    op.drop_index(op.f('ix_sirius_role_id'), table_name='role', schema='sirius')
    op.drop_table('role', schema='sirius')
    # ### end Alembic commands ###
